Throw errors instead of objects.
Passing objects to `reject` just causes q to re-throw the error with a snarky emoticon:

Error: the object {
  "exception": {
    "$": {
      "xmlns:xsd": "http://www.w3.org/2001/XMLSchema"
      "xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance"
    }
    "Elements": {
      "DataContractBase": {
        "$": {
          "xsi:type": "Account"
        }
        "AccountID": "00000000-0000-0000-0000-000000000000"
        "Code": "TESTPAY"
        "EnablePaymentsToAccount": "true"
        "Name": "Test account from Node SDK"
        "Type": "SALES"
        "ValidationErrors": {
          "ValidationError": [
            {
              "Message": "Please enter a unique Code."
            }
            {
              "Message": "Please enter a unique Name."
            }
          ]
        }
      }
    }
    "ErrorNumber": "10"
    "Message": "A validation exception occurred"
    "Type": "ValidationException"
  }
  "statusCode": 400
} was thrown, throw an Error :)